baseURL = "http://docomo-cycle.com/"
languageCode = "ja-JP"
title = "#自転車のある風景"
theme = "photo-grid"

# github pages対応
publishDir = "docs"
canonifyurls = true

[params]
    # Meta
    no_exif = false
    title = "a landscape picture with a bicycle"
    # subtitle = "I'd like to collect landscape photos of bicycles."
    author = "docomo-cycle.com"
    description = "docomo-cycle Gallery"
    keywords = "docomo-cycle, share bike, bike share, 赤チャリ"

    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer
    copyright_since_year = 2013
    copyright_text = "All images"

